// One-shot importer for the Aitsa! customer export CSV.
// Reads CustomerExport (1).csv at the repo root, filters rows whose Category
// looks like a grade ("NN - Grade X"), maps fields, and emits a SQL file
// you can paste into the Supabase SQL Editor.
//
// Usage:
//   node scripts/import_learners.mjs
//   → writes scripts/import_learners.sql
//
// Re-runs are safe-ish: rows are inserted with UUIDs, so running it twice
// will produce duplicates. If you need to re-run, truncate the table first
// (SQL Editor: `truncate public.learners cascade;`).

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const csvPath = resolve(here, "..", "CustomerExport (1).csv");
const sqlOut = resolve(here, "import_learners.sql");

function parseCsvLine(line) {
  // Minimal RFC-4180-ish parser: handles quoted fields and embedded commas.
  const out = [];
  let cur = "";
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQ) {
      if (c === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (c === '"') {
        inQ = false;
      } else cur += c;
    } else if (c === '"') inQ = true;
    else if (c === ",") {
      out.push(cur);
      cur = "";
    } else cur += c;
  }
  out.push(cur);
  return out.map((s) => s.trim());
}

function gradeFromCategory(cat) {
  // "01 - Grade R" → "Grade R"
  // "02 - Grade 1" → "Grade 1"
  const m = cat.match(/Grade\s*([R\d]+)/i);
  if (!m) return null;
  return `Grade ${m[1].toUpperCase()}`;
}

function splitName(raw) {
  // "Meagan Louw (Imbali)" → first="Meagan", last="Louw", note="Imbali"
  // "Lily-Ane Lottering"   → first="Lily-Ane", last="Lottering"
  // "Sue"                  → first="Sue", last=""
  let note = null;
  const parenMatch = raw.match(/^(.*?)\s*\(([^)]+)\)\s*$/);
  let name = raw;
  if (parenMatch) {
    name = parenMatch[1].trim();
    note = parenMatch[2].trim();
  }
  const parts = name.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return null;
  if (parts.length === 1) return { first: parts[0], last: "", note };
  const first = parts[0];
  const last = parts.slice(1).join(" ");
  return { first, last, note };
}

function escSql(v) {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
}

const raw = readFileSync(csvPath, "utf8").replace(/^﻿/, "");
const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
const header = parseCsvLine(lines[0]);
const idx = {
  name: header.indexOf("Name"),
  category: header.indexOf("Category"),
  active: header.indexOf("Active"),
};
if (idx.name < 0 || idx.category < 0 || idx.active < 0) {
  console.error("Unexpected CSV header:", header);
  process.exit(1);
}

const rows = [];
let skipped = 0;
for (let i = 1; i < lines.length; i++) {
  const cells = parseCsvLine(lines[i]);
  const grade = gradeFromCategory(cells[idx.category] ?? "");
  if (!grade) {
    skipped++;
    continue;
  }
  const split = splitName(cells[idx.name] ?? "");
  if (!split) {
    skipped++;
    continue;
  }
  const active = (cells[idx.active] ?? "").toLowerCase() === "yes";
  rows.push({
    first_name: split.first,
    last_name: split.last || "(unknown)",
    grade,
    active,
    notes: split.note ? `Imported alias: ${split.note}` : null,
  });
}

const lines_out = [
  "-- Generated by scripts/import_learners.mjs from CustomerExport (1).csv.",
  "-- Paste this into Supabase SQL Editor and run.",
  "-- The SQL Editor runs as the postgres role and bypasses RLS.",
  "",
  "begin;",
  "",
  "insert into public.learners (first_name, last_name, grade, active, notes) values",
];

const valueLines = rows.map((r, i) => {
  const tail = i === rows.length - 1 ? ";" : ",";
  return `  (${escSql(r.first_name)}, ${escSql(r.last_name)}, ${escSql(r.grade)}, ${escSql(r.active)}, ${escSql(r.notes)})${tail}`;
});

lines_out.push(...valueLines, "", "commit;", "");
writeFileSync(sqlOut, lines_out.join("\n"));

console.log(`Parsed ${rows.length} learners, skipped ${skipped} non-learner rows.`);
console.log(`Wrote SQL to: ${sqlOut}`);
const grades = new Map();
for (const r of rows) grades.set(r.grade, (grades.get(r.grade) ?? 0) + 1);
console.log("By grade:");
for (const [g, n] of [...grades.entries()].sort()) console.log(`  ${g}: ${n}`);
